'use client'
import { useEffect, useMemo, useState } from 'react'
import Header from '@/components/Header';import TaxTabs from '@/components/TaxTabs';import FilterBar,{Filters} from '@/components/FilterBar';import ExcelUploader from '@/components/ExcelUploader';import UploadHistory from '@/components/UploadHistory';import SummaryCards from '@/components/SummaryCards';import DataQuality from '@/components/DataQuality';import TaxTable from '@/components/TaxTable';import ManualEntryModal from '@/components/ManualEntryModal'
import { TaxRecord, UploadHistoryItem } from '@/utils/excelParser';import { calculateSummary, filterByMenu } from '@/utils/taxCalculations'
const dummy:TaxRecord[]=[
{id:'d1',perusahaan:'PT Maju Pajak',masa_pajak:'Januari',tahun:'2026',jenis_pajak:'PPN Keluaran',dpp:120000000,pajak_terhutang:13200000,ntpn_ntpd:'NTPN001',status:'Sudah Bayar',source:'Dummy',keterangan:'Data awal',errors:[]},
{id:'d2',perusahaan:'PT Maju Pajak',masa_pajak:'Januari',tahun:'2026',jenis_pajak:'PPN Masukan',dpp:45000000,pajak_terhutang:4950000,ntpn_ntpd:'NTPN002',status:'Sudah Bayar',source:'Dummy',keterangan:'Dikreditkan',errors:[]},
{id:'d3',perusahaan:'CV Sejahtera',masa_pajak:'Februari',tahun:'2026',jenis_pajak:'PPh Pasal 21',dpp:80000000,pajak_terhutang:4000000,ntpn_ntpd:'',status:'Belum memiliki NTPN/NTPD',source:'Dummy',keterangan:'Menunggu pembayaran',errors:[]},
{id:'d4',perusahaan:'Resto Nusantara',masa_pajak:'Maret',tahun:'2026',jenis_pajak:'PB1',dpp:65000000,pajak_terhutang:6500000,ntpn_ntpd:'NTPD009',status:'Sudah Bayar',source:'Dummy',keterangan:'Pajak restoran',errors:[]},
{id:'d5',perusahaan:'UMKM Berkah',masa_pajak:'April',tahun:'2026',jenis_pajak:'PPh UMKM',dpp:30000000,pajak_terhutang:150000,ntpn_ntpd:'',status:'Belum memiliki NTPN/NTPD',source:'Dummy',keterangan:'Belum setor',errors:[]}
]
const defaultFilters:Filters={tahun:'',masa:'',perusahaan:'',jenis:'',status:''}
export default function Page(){const[rows,setRows]=useState<TaxRecord[]>(dummy);const[history,setHistory]=useState<UploadHistoryItem[]>([]);const[active,setActive]=useState('Dashboard');const[filters,setFilters]=useState(defaultFilters);const[manual,setManual]=useState(false);useEffect(()=>{const saved=localStorage.getItem('taxRows');const savedHist=localStorage.getItem('taxHistory');if(saved)setRows(JSON.parse(saved));if(savedHist)setHistory(JSON.parse(savedHist))},[]);useEffect(()=>{localStorage.setItem('taxRows',JSON.stringify(rows))},[rows]);useEffect(()=>{localStorage.setItem('taxHistory',JSON.stringify(history))},[history]);function onUpload(fileName:string,data:TaxRecord[]){setRows([...data,...rows]);setHistory([{id:`hist-${Date.now()}`,fileName,uploadedAt:new Date().toISOString(),rowCount:data.length,errorCount:data.filter(r=>r.errors.length).length,data},...history])}
const scoped=useMemo(()=>{let d=filterByMenu(rows,active);return d.filter(r=>(!filters.tahun||r.tahun.includes(filters.tahun))&&(!filters.masa||r.masa_pajak.toLowerCase().includes(filters.masa.toLowerCase()))&&(!filters.perusahaan||r.perusahaan===filters.perusahaan)&&(!filters.jenis||r.jenis_pajak===filters.jenis)&&(!filters.status||r.status===filters.status))},[rows,active,filters]);const companies=[...new Set(rows.map(r=>r.perusahaan).filter(Boolean))];const taxTypes=[...new Set(rows.map(r=>r.jenis_pajak).filter(Boolean))];return <main className="mx-auto max-w-7xl space-y-6 p-4 md:p-8"><Header/><TaxTabs active={active} onChange={setActive}/><FilterBar filters={filters} setFilters={setFilters} companies={companies} taxTypes={taxTypes}/><div className="grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><ExcelUploader onUpload={onUpload}/><UploadHistory history={history} onView={(data)=>setRows(data)} onDelete={(id)=>setHistory(history.filter(h=>h.id!==id))}/></div><div className="flex justify-end"><button onClick={()=>setManual(true)} className="rounded-2xl bg-blue-600 px-5 py-3 font-bold text-white shadow-lg">Tambah Data Pajak Manual</button></div><SummaryCards items={calculateSummary(scoped)}/><DataQuality rows={scoped}/><TaxTable rows={scoped} setRows={(nextScoped)=>{const ids=new Set(scoped.map(r=>r.id));setRows([...rows.filter(r=>!ids.has(r.id)),...nextScoped])}}/><ManualEntryModal open={manual} onClose={()=>setManual(false)} onSave={(r)=>setRows([r,...rows])}/></main>}
