import * as XLSX from 'xlsx'
import { normalizeText, parseNumber } from './formatters'
export type TaxRecord = { id: string; perusahaan: string; masa_pajak: string; tahun: string; jenis_pajak: string; dpp: number; pajak_terhutang: number; ntpn_ntpd: string; status: string; source: string; keterangan: string; errors: string[] }
export type UploadHistoryItem = { id: string; fileName: string; uploadedAt: string; rowCount: number; errorCount: number; data: TaxRecord[] }
const aliases: Record<keyof Omit<TaxRecord,'id'|'errors'>, string[]> = {
  perusahaan:['perusahaan','nama perusahaan','company'], masa_pajak:['masa pajak','masa','bulan'], tahun:['tahun','year'], jenis_pajak:['jenis pajak','pajak','tax type'], dpp:['dpp','dasar pengenaan pajak'], pajak_terhutang:['pajak terhutang','pajak terutang','nominal pajak','jumlah pajak'], ntpn_ntpd:['ntpn','ntpd','ntpn/ntpd','nomor bukti bayar'], status:['status','status bayar','payment status'], source:['source','sumber data'], keterangan:['keterangan','notes','catatan']
}
function normHeader(header: string) { return header.toLowerCase().replace(/[_-]/g,' ').replace(/\s+/g,' ').trim() }
function pick(row: Record<string, unknown>, target: keyof typeof aliases) { const found = Object.keys(row).find((key) => aliases[target].includes(normHeader(key))); return found ? row[found] : '' }
export function normalizeRows(rows: Record<string, unknown>[], source = 'Excel'): TaxRecord[] { return rows.map((row, index) => { const ntpn = normalizeText(pick(row,'ntpn_ntpd')); const statusInput = normalizeText(pick(row,'status')); const record: TaxRecord = { id: `${Date.now()}-${index}-${Math.random().toString(36).slice(2)}`, perusahaan: normalizeText(pick(row,'perusahaan')), masa_pajak: normalizeText(pick(row,'masa_pajak')), tahun: normalizeText(pick(row,'tahun')), jenis_pajak: normalizeText(pick(row,'jenis_pajak')), dpp: parseNumber(pick(row,'dpp')), pajak_terhutang: parseNumber(pick(row,'pajak_terhutang')), ntpn_ntpd: ntpn, status: ntpn ? 'Sudah Bayar' : (statusInput || 'Belum memiliki NTPN/NTPD'), source: normalizeText(pick(row,'source')) || source, keterangan: normalizeText(pick(row,'keterangan')), errors: [] }
 const errors = []; if (!record.perusahaan) errors.push('Perusahaan kosong'); if (!record.jenis_pajak) errors.push('Jenis pajak kosong'); if (!record.masa_pajak) errors.push('Masa pajak kosong'); if (!record.tahun) errors.push('Tahun kosong'); if (!record.pajak_terhutang) errors.push('Nominal pajak kosong/0'); record.errors = errors; return record }) }
export async function parseExcelFile(file: File): Promise<TaxRecord[]> { const buffer = await file.arrayBuffer(); const workbook = XLSX.read(buffer); const first = workbook.SheetNames[0]; if (!first) throw new Error('File Excel tidak memiliki sheet.'); const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(workbook.Sheets[first], { defval: '' }); return normalizeRows(rows, file.name) }
export function makeExampleWorkbook() { const data = [{ Perusahaan:'PT Contoh Nusantara', 'Masa Pajak':'Januari', Tahun:'2026', 'Jenis Pajak':'PPN Keluaran', DPP:100000000, 'Pajak Terhutang':11000000, NTPN:'ABC123', Source:'Template', Keterangan:'Contoh lunas' },{ Company:'CV Demo', Bulan:'Februari', Year:'2026', 'Tax Type':'PPh Pasal 21', 'Dasar Pengenaan Pajak':50000000, 'Jumlah Pajak':2500000, 'Nomor Bukti Bayar':'', 'Sumber Data':'Template', Catatan:'Belum bayar' }]; const ws = XLSX.utils.json_to_sheet(data); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'Template Pajak'); XLSX.writeFile(wb, 'template-upload-pajak.xlsx') }
export function exportTaxRows(rows: TaxRecord[], fileName='resume-pembayaran-pajak.xlsx') { const clean = rows.map(({errors,id,...r}) => r); const ws = XLSX.utils.json_to_sheet(clean); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, 'Resume Pajak'); XLSX.writeFile(wb, fileName) }
